openapi: 3.0.3
info:
  title: Currícula docs
  description: |-
    Especificación de la API de Currícula
  version: 1.1.0
servers:
  - url: http://localhost:8080/curricula_microservice
    description: Server
paths:
  /Estudiante:
    get:
      summary: Crear modelo de estudiante
      operationId: createStudentModel
      parameters:
        - name: name
          in: query
          description: Nombre de Estudiante
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: ID de Estudiante
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Estudiante'
  /Faculty:
    get:
      summary: Obtener información de una facultad
      operationId: getFaculty
      parameters:
        - name: faculty
          in: query
          description: Nombre de Facultad
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Facultad'
        '404':
          description: Facultad not found
  /Faculty/ucs:
    get:
      summary: Obtener información de una UC
      operationId: getuc
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: uc
          in: query
          description: Id de UC
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uc'
        '404':
          description: uc not found
  /Faculty/Carrera:
    get:
      summary: Obtener información de una carrera
      operationId: getCarrera
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: career
          in: query
          description: Nombre de carrera
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Carrera'
        '404':
          description: Career not found
  /Faculty/Carrera/Plan:
    get:
      summary: Obtener información de un plan
      operationId: getPlan
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: career
          in: query
          description: Nombre de carrera
          required: true
          schema:
            type: string
        - name: plan
          in: query
          description: Plan
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plan'
        '404':
          description: Plan not found
  /Faculty/Carrera/Plan/ucs:
    get:
      summary: Obtener información de las UCs de un plan
      operationId: getUCPlan
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: career
          in: query
          description: Nombre de carrera
          required: true
          schema:
            type: string
        - name: plan
          in: query
          description: Plan
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: GAL1
        '404':
          description: Plan not found
  /Faculty/Carrera/Plan/Subjects:
    get:
      summary: Obtener información de una materia en un plan
      operationId: getPlanSubject
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: career
          in: query
          description: Nombre de carrera
          required: true
          schema:
            type: string
        - name: plan
          in: query
          description: Plan
          required: true
          schema:
            type: integer
        - name: subject
          in: query
          description: Nombre de materia
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/materia'
        '404':
          description: subject not found
  /Estudiante/AddPlan:
    post:
      summary: Agrega una inscripción a plan a un modelo de estudiante
      operationId: addStudentPlan
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: career
          in: query
          description: Nombre de carrera
          required: true
          schema:
            type: string
        - name: plan
          in: query
          description: Id de plan
          required: true
          schema:
            type: integer
        - name: date
          in: query
          description: Fecha de inscripción
          required: true
          schema:
            type: string
      requestBody:
        description: Modelo .xmi de estudiante
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/RootEstudiante'
      responses:
        '200':
          description: Success
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RootEstudiante'
        '404':
          description: Plan not found
  /Estudiante/AddEvaluation:
    post:
      summary: Agrega una evaluación a un modelo de estudiante
      operationId: addStudentEval
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: career
          in: query
          description: Nombre de carrera
          required: true
          schema:
            type: string
        - name: plan
          in: query
          description: Id de plan
          required: true
          schema:
            type: integer
        - name: curricularUnit
          in: query
          description: Id de UC
          required: true
          schema:
            type: string
        - name: evaluation
          in: query
          description: Id de evaluación
          required: true
          schema:
            type: string
        - name: nota
          in: query
          description: Nota obtenida
          required: true
          schema:
            type: integer
      requestBody:
        description: Modelo .xmi de estudiante
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/RootEstudiante'
      responses:
        '200':
          description: Success
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RootEstudiante'
        '404':
          description: Subject not found
  /Faculty/ucs/eval:
    post:
      summary: Evalúa los requerimientos de un estudiante en una UC en específico en el modelo
      operationId: eval
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: curricularUnit
          in: query
          description: Id de UC
          required: true
          schema:
            type: string
      requestBody:
        description: Modelo .xmi de estudiante
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/RootEstudiante'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '404':
          description: Subject not found
  /Faculty/Carrera/Plan/eval:
    post:
      summary: Evalúa qué UCs puede cursar un estudiante
      operationId: evalPlan
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: career
          in: query
          description: Nombre de carrera
          required: true
          schema:
            type: string
        - name: plan
          in: query
          description: Plan
          required: true
          schema:
            type: integer
      requestBody:
        description: Modelo de estudiante
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/RootEstudiante'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: CDIV
        '400':
          description: Malformed request
        '404':
          description: Plan not found
  /Faculty/Carrera/Plan/evaluations:
    post:
      summary: No se que hace consultar ni porque esta programada como esta, consultar a Santiago Freire, no se usa
      operationId: evaluations
      parameters:
        - name: faculty
          in: query
          description: Nombre de facultad
          required: true
          schema:
            type: string
        - name: career
          in: query
          description: Nombre de carrera
          required: true
          schema:
            type: string
        - name: plan
          in: query
          description: Plan
          required: true
          schema:
            type: integer
      requestBody:
        description: Modelo .xmi de estudiante
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/RootEstudiante'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EvaluationAbstract'
        '404':
          description: Plan not found
components:
  schemas:
    uc:
      required:
        - name
        - id
      type: object
      properties:
        Name:
          type: string
          example: CALCULO DIV
        Id:
          type: string
          example: 1061
        Cred:
          type: integer
          example: 13
        Requirement:
            $ref: '#/components/schemas/Requerimiento'
        Course:
          type: array
          items:
            $ref: '#/components/schemas/Course'
        ExamEvaluation:
          type: array
          items:
            $ref: '#/components/schemas/ExamEvaluation'
    Course:
      type: object
      properties:
        year:
          type: integer
          example: 2023
        edition:
          type: integer
          example: 0
        courseEvaluations:
          type: array
          items:
            $ref: '#/components/schemas/CourseEvaluation'
    Facultad:
      required:
        - name
      type: object
      properties:
        Name:
          type: string
          example: Facultad de Ingenieria
        Careers:
          type: array
          items:
            type: string
            example: Ing. Computacion
        FacultyCU:
          type: array
          items:
            type: string
            example: CDIV
    Carrera:
      required:
        - name
      type: object
      properties:
        Name:
          type: string
          example: Ing. En Computacion
        Plans:
          type: array
          items:
            type: integer
            example: 1997
    PlanAbstract:
      type: object
      required:
        - year
      properties:
        Year:
          type: integer
          example: 1997
        Career:
          type: string
          example: Ing. Computacion
        Type:
          type: string
          example: CreditsPlan
    Plan:
      oneOf:
        - $ref: '#/components/schemas/PlanCreditos'
        - $ref: '#/components/schemas/Planucs'
    PlanCreditos:
      allOf:
        - $ref: '#/components/schemas/PlanAbstract'
        - type: object
          properties:
            MinCredits:
              type: integer
            Subjects:
              type: array
              items:
                type: string
                example: 4083
    Planucs:
      allOf:
        - $ref: '#/components/schemas/PlanAbstract'
        - type: object
          properties:
            "Curricular Units":
              type: array
              items:
                type: string
                example: 1061
    materia:
      type: object
      required:
        - id
        - name
      properties:
        Id:
          type: integer
          example: 4083
        Name:
          type: string
          example: MATEMATICA
        MinCredits:
          type: integer
          example: 70
        CurricularUnits:
          type: array
          items:
            type: string
            example: 1030
        Subjects:
          type: array
          items:
            $ref: '#/components/schemas/materia'
    Requerimiento:
      type: string
    EvaluationFather:
      type: object
      required:
        - date
      properties:
        date:
          type: string
          example: "0001-01-01T00:00:00.000-0300"
    Evaluation:
      type: object
      properties:
        type:
          type: string
          example: "asignaturas:CourseEvaluation"
          xml:
            attribute: true
        href:
          type: string
          example: "model.xmi#//@Faculty.0/@FacultyCU.0/@Course.0/@CourseEvaluation.0"
          xml:
            attribute: true
    EvaluationAbstract:
      oneOf:
        - $ref: '#/components/schemas/ExamEvaluation'
        - $ref: '#/components/schemas/CourseEvaluation'
    ExamEvaluation:
      $ref: '#/components/schemas/EvaluationFather'
    CourseEvaluation:
      $ref: '#/components/schemas/EvaluationFather'
    RootEstudiante:
      type: object
      properties:
        Student:
          $ref: '#/components/schemas/Estudiante'
    PlanInscription:
      type: object
      required:
        - date
      properties:
        plan:
          type: object
          required:
            - "type"
            - href
          properties:
            "type":
              type: string
              example: "asignaturas:CreditsPlan"
              xml:
                attribute: true
            href:
              type: string
              example: "model.xmi#//@Faculty.0/@Careers.0/@plan.0"
              xml:
                attribute: true
        date:
          type: string
          example: "0001-01-01T00:00:00.000-0300"
          xml:
            attribute: true
        PlanCourseInscription:
          type: array
          items:
            $ref: '#/components/schemas/PlanCourseInscription'
        PlanStudentEvaluation:
          type: array
          items:
            $ref: '#/components/schemas/PlanStudentEvaluation'
    PlanCourseInscription:
      type: object
      required:
        - date
      properties:
        CUCourse:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              example: "model.xmi#//@Faculty.0/@FacultyCU.0/@Course.0"
              xml:
                attribute: true
        date:
          type: string
          example: "0001-01-01T00:00:00.000-0300"
          xml:
            attribute: true
    PlanStudentEvaluation:
      type: object
      required:
        - grade
        - evaluation
      properties:
        grade:
          type: integer
          example: 6
          xml:
            attribute: true
        evaluation:
          $ref: '#/components/schemas/Evaluation'
    Estudiante:
      type: object
      required:
        - id
        - name
        - carrera
      properties:
        id:
          type: string
          example: test
          xml:
            attribute: true
        name:
          type: string
          example: fulano
          xml:
            attribute: true
        StudentPlanInscription:
          type: array
          items:
            $ref: '#/components/schemas/PlanInscription'
