name: Build Curricula Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Ant
      run: sudo apt-get install -y ant

    - name: Compile Classes
      run: ant -f proyecto/java_microservice/build.xml build-project
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-classes
        path: proyecto/java_microservice/build

  build_war:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Ant
      run: sudo apt-get install -y ant

    - name: Download Compiled Classes
      uses: actions/download-artifact@v4
      with:
        name: compiled-classes
        path: proyecto/java_microservice/build

    - name: Build WAR
      run: ant -f proyecto/java_microservice/build.xml build-war

    - name: Upload WAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: curricula_microservice.war
        path: proyecto/java_microservice/dist/curricula_microservice.war
